[package]
name = "nufmt"
version = "0.1.0"
edition = "2018"
authors = ["The NuShell Contributors"]
license = "MIT"
description = "Formats nushell extremely fast"
homepage = "https://github.com/fdncred/nufmt"
repository = "https://github.com/fdncred/nufmt"
readme = "README.md"
keywords = ["nu", "nushell", "formatting", "cli"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version= "2.33.3", optional = true }

[dev-dependencies]
criterion = "0.3"

[features]
default = ["bin"]
bin = ["clap"]

[lib]
name = "nufmt"
path = "src/lib.rs"

[[bin]]
name = "nufmt"
path = "src/main.rs"
required-features = ["bin"]

[[bench]]
name = "bench"
harness = false
